image: joepol/bootcamp-image:test8
tasks:
  - name: Start algodeploy
    init: ~/algodeploy/algodeploy.py start
  - name: Start indexer
    init: psql -c 'create database indexer;'
    command: |
      sleep 5 && algorand-indexer daemon \
      --loglevel info \
      --postgres "host=localhost port=5432 user=gitpod dbname=indexer sslmode=disable" \
      --algod-net "localhost:4001" \
      --algod-token "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
      --data-dir ~/.algodeploy/localnet/data/Node \
      --dev-mode
vscode:
  extensions:
    - ms-python.python