image: joepol/algorand-gitpod:algokit
tasks:
  - name: algokit sandbox
    command: algokit sandbox start
  - name: dappflow
    command: gp ports await 8980 && gp ports await 4001 && serve -s ~/dappflow/
vscode:
  extensions:
    - ms-python.python
ports:
  - name: dappflow
    port: 3000
    onOpen: open-preview
  - name: algod
    port: 4001
    visibility: public
    onOpen: ignore
  - name: indexer
    port: 8980
    visibility: public
    onOpen: ignore
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: kmd
    port: 4002
    onOpen: ignore