image: joepol/bootcamp-image:test9
tasks:
  - name: Algodeploy
    command: ~/algodeploy/algodeploy.py start
  - name: Indexer
    init: psql -c 'create database indexer;'
    command: |
      sleep 5 && algorand-indexer daemon \
      --loglevel info \
      --postgres "host=localhost port=5432 user=gitpod dbname=indexer sslmode=disable" \
      --algod-net "localhost:4001" \
      --algod-token "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
      --data-dir ~/.algodeploy/localnet/data/Node \
      --dev-mode
  - name: Dappflow
    command: serve -s ~/dappflow/build
vscode:
  extensions:
    - ms-python.python
ports:
  - name: Dappflow
    port: 3000
    onOpen: open-browser
  - name: algod
    port: 4001
    visibility: public
    onOpen: ignore
  - name: indexer
    port: 8980
    visibility: public
    opOpen: ignore
  - name: postgres
    port: 5432
    opOpen: ignore
  - name: kmd
    port: 4002
    opOpen: ignore